-- CreateTable
CREATE TABLE `M_AGAMA` (
    `KODE_AGAMA` TINYINT NOT NULL,
    `NAMA_AGAMA` CHAR(10) NOT NULL,
    `CREATE_USER` VARCHAR(30) NOT NULL,
    `CREATE_DATE` DATETIME(0) NOT NULL,
    `UPDATE_USER` VARCHAR(30) NULL,
    `UPDATE_DATE` DATETIME(0) NULL,

    PRIMARY KEY (`KODE_AGAMA`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `M_DATI2` (
    `KODE_MPRO` VARCHAR(20) NOT NULL,
    `KODE_MDATI` VARCHAR(20) NOT NULL,
    `NAMA_MDATI` VARCHAR(100) NOT NULL,
    `ALIAS_MDATI` VARCHAR(50) NULL,
    `STATUS_AKTIF` TINYINT NULL,
    `CREATE_USER` VARCHAR(30) NOT NULL,
    `CREATE_DATE` DATETIME(0) NOT NULL,
    `UPDATE_USER` VARCHAR(30) NULL,
    `UPDATE_DATE` DATETIME(0) NULL,

    PRIMARY KEY (`KODE_MPRO`, `KODE_MDATI`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `M_KECAMATAN` (
    `KODE_MPRO` VARCHAR(20) NOT NULL,
    `KODE_MDATI` VARCHAR(20) NOT NULL,
    `KODE_MKEC` VARCHAR(20) NOT NULL,
    `NAMA_MKEC` VARCHAR(100) NOT NULL,
    `ALIAS_MKEC` VARCHAR(50) NULL,
    `STATUS_AKTIF` TINYINT NULL,
    `CREATE_USER` VARCHAR(30) NOT NULL,
    `CREATE_DATE` DATETIME(0) NOT NULL,
    `UPDATE_USER` VARCHAR(30) NULL,
    `UPDATE_DATE` DATETIME(0) NULL,

    PRIMARY KEY (`KODE_MPRO`, `KODE_MDATI`, `KODE_MKEC`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `M_KELURAHAN` (
    `KODE_MPRO` VARCHAR(20) NOT NULL,
    `KODE_MDATI` VARCHAR(20) NOT NULL,
    `KODE_MKEC` VARCHAR(20) NOT NULL,
    `KODE_MKEL` VARCHAR(20) NOT NULL,
    `NAMA_MKEL` VARCHAR(100) NULL,
    `ALIAS_MKEL` VARCHAR(50) NULL,
    `STATUS_AKTIF` TINYINT NULL,
    `CREATE_USER` VARCHAR(30) NOT NULL,
    `CREATE_DATE` DATETIME(0) NOT NULL,
    `UPDATE_USER` VARCHAR(30) NULL,
    `UPDATE_DATE` DATETIME(0) NULL,

    PRIMARY KEY (`KODE_MPRO`, `KODE_MDATI`, `KODE_MKEC`, `KODE_MKEL`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `M_PROPINSI` (
    `KODE_MPRO` VARCHAR(20) NOT NULL,
    `NAMA_MPRO` VARCHAR(100) NOT NULL,
    `ALIAS_MPRO` VARCHAR(20) NULL,
    `KODEPETA_MPRO` VARCHAR(10) NULL,
    `STATUS_AKTIF` TINYINT NULL,
    `CREATE_USER` VARCHAR(30) NOT NULL,
    `CREATE_DATE` DATETIME(0) NOT NULL,
    `UPDATE_USER` VARCHAR(30) NULL,
    `UPDATE_DATE` DATETIME(0) NULL,

    PRIMARY KEY (`KODE_MPRO`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `M_USER` (
    `UUID` VARCHAR(50) NOT NULL,
    `KODE_AGAMA` TINYINT NULL,
    `KODE_MPRO` VARCHAR(20) NULL,
    `KODE_MDATI` VARCHAR(20) NULL,
    `KODE_MKEC` VARCHAR(20) NULL,
    `KODE_MKEL` VARCHAR(20) NULL,
    `USER_NAME` VARCHAR(50) NULL,
    `USER_EMAIL` VARCHAR(50) NULL,
    `USER_PASSWORD` VARCHAR(60) NULL,
    `USER_NIK` VARCHAR(20) NULL,
    `USER_TTL` DATE NULL,
    `USER_NOTELP` VARCHAR(20) NULL,
    `USER_WA` VARCHAR(20) NULL,
    `USER_ADDRESS` VARCHAR(50) NULL,
    `USER_PHOTOKTP` VARCHAR(20) NULL,
    `USER_PHOTOSELFIE` VARCHAR(20) NULL,
    `USER_FACERECOGNITION` VARCHAR(20) NULL,
    `USER_GENDER` VARCHAR(20) NULL,
    `USER_STATUSPERNIKAHAN` VARCHAR(20) NULL,
    `USER_KEWARGANEGARAAN` TINYINT NULL,
    `USER_NPWP` VARCHAR(20) NULL,
    `CREATE_DATE` DATETIME(0) NOT NULL,
    `UPDATE_DATE` DATETIME(0) NULL,

    PRIMARY KEY (`UUID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `M_BANK` (
    `KODE_MBANK` VARCHAR(20) NOT NULL,
    `NAMA_MBANK` VARCHAR(50) NOT NULL DEFAULT '0',
    `NOMOR_REKENING` VARCHAR(50) NULL,
    `NOMOR_KARTU` VARCHAR(50) NULL,
    `VALID_TAHUN` VARCHAR(4) NOT NULL,
    `VALID_BULAN` VARCHAR(2) NOT NULL,
    `USER_CCV` VARCHAR(3) NOT NULL DEFAULT '0',
    `BUKU_REKENING` VARCHAR(30) NULL,
    `STATUS_AKTIF` TINYINT NULL,
    `CREATE_USER` VARCHAR(36) NOT NULL,
    `CREATE_DATE` DATETIME(0) NOT NULL,
    `UPDATE_USER` VARCHAR(36) NULL,
    `UPDATE_DATE` DATETIME(0) NULL,

    PRIMARY KEY (`KODE_MBANK`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `M_WALLET` (
    `KODE_MWALLET` VARCHAR(20) NOT NULL,
    `USER_SALDO` INTEGER NULL DEFAULT 0,
    `USER_WITHDRAWL` INTEGER NULL,
    `USER_DEPOSIT` INTEGER NULL,
    `STATUS_AKTIF` TINYINT NULL,
    `CREATE_USER` VARCHAR(36) NOT NULL,
    `CREATE_DATE` DATETIME(0) NOT NULL,
    `UPDATE_USER` VARCHAR(36) NULL,
    `UPDATE_DATE` DATETIME(0) NULL,
    `KODE_MBANK` VARCHAR(20) NULL,

    PRIMARY KEY (`KODE_MWALLET`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
